name: Build and Push Quarkus Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Force Native Object Sync
        run: |
          # 2. Clear the restrictive refspec GitHub sets by default
          git config --unset-all remote.origin.fetch || true
          
          # 3. Set the exact standard refspec your local machine uses
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          
          # 4. Force a raw fetch of ALL refs and tags down to the object level
          git fetch --prune --tags --force origin

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push with Jib
        run: |
          git describe --tags --always
          RAW_TAGS=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. '{print $1 "," $1"."$2 "," $1"."$2"."$3}')
          echo "Raw tags: $RAW_TAGS"
#          ./mvnw clean package \
#            -DskipTests \
#            -Dquarkus.container-image.build=true \
#            -Dquarkus.container-image.push=true \
#            -Dquarkus.container-image.builder=jib \
#            -Dquarkus.container-image.registry=ghcr.io \
#            -Dquarkus.container-image.group=${{ github.repository_owner }} \
#            -Dquarkus.container-image.name=${{ github.event.repository.name }} \
#            -Dquarkus.container-image.tag=latest \
#            -Dquarkus.container-image.additional-tags=$RAW_TAGS
